apiVersion: v1
kind: Service
metadata:
  name: nginx-v4-only
  labels:
    app: nginx
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-v6-only
  labels:
    app: nginx
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv6
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80


