apiVersion: v1
kind: Service
metadata:
  name: nginx-ds-v4
  labels:
    app: nginx
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
  - IPv4
  - IPv6
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ds-v6
  labels:
    app: nginx
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
  - IPv6
  - IPv4
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80


